// nav items list

export const navData: NavLink[] = [
  {
    label: "Home",
    href: "/",
  },
  {
    label: "Products",
    href: "/pu/products",
  },
  {
    label: "Privacy Policy",
    href: "/pu/privacy",
  },
  {
    label: "Contact Us",
    href: "/pu/contact",
  },
  {
    label: "About",
    href: "/pu/about",
  },

  {
    label: "FAQs",
    href: "/pu/faqs",
  },
];

// product samples
export const productSamples = [
  {
    name: "Organic Chicken Dog Food",
    description:
      "Premium grain-free chicken recipe for adult dogs. Packed with organic ingredients.",
    sku: "DOGFOOD-CHICK-001",
    barcode: "0123456789012",
    price: 24.99,
    salePrice: 19.99,
    image: "https://example.com/images/dogfood_chicken.jpg",
    images: [
      "https://example.com/images/dogfood_chicken1.jpg",
      "https://example.com/images/dogfood_chicken2.jpg",
    ],
    stockQuantity: 150,
    isActive: true,
    tags: ["dog", "food", "organic", "grain-free"],
    ownerId: "store_paw",
  },
  {
    name: "Catnip Mouse Toy",
    description:
      "Soft plush mouse toy filled with potent North American catnip.",
    sku: "CATTOY-MOUSE-001",
    barcode: "1234567890123",
    price: 5.49,
    salePrice: null,
    image: "https://example.com/images/catnip_mouse.jpg",
    images: ["https://example.com/images/catnip_mouse1.jpg"],
    stockQuantity: 300,
    isActive: true,
    tags: ["cat", "toy", "catnip"],
    ownerId: "store_purr",
  },
  {
    name: "Adjustable Dog Harness (Medium)",
    description: "Breathable and adjustable harness for daily dog walks.",
    sku: "DOGHARNESS-MED-001",
    barcode: "2345678901234",
    price: 18.99,
    salePrice: 16.99,
    image: "https://example.com/images/dog_harness.jpg",
    images: [
      "https://example.com/images/dog_harness1.jpg",
      "https://example.com/images/dog_harness2.jpg",
    ],
    stockQuantity: 80,
    isActive: true,
    tags: ["dog", "harness", "walking"],
    ownerId: "store_paw",
  },
  {
    name: "Aquarium Water Conditioner",
    description:
      "Dechlorinates tap water instantly; safe for fish and aquatic plants.",
    sku: "FISHCARE-WATER-001",
    barcode: "3456789012345",
    price: 9.95,
    salePrice: 8.5,
    image: "https://example.com/images/water_conditioner.jpg",
    images: [],
    stockQuantity: 200,
    isActive: true,
    tags: ["fish", "aquarium", "water treatment"],
    ownerId: "store_aqua",
  },
  {
    name: "Rabbit Hay Feeder",
    description:
      "Wall-mounted hay feeder for small pets—keeps hay clean and accessible.",
    sku: "SMALLPET-HAY-001",
    barcode: "4567890123456",
    price: 13.99,
    salePrice: null,
    image: "https://example.com/images/rabbit_hay_feeder.jpg",
    images: ["https://example.com/images/rabbit_hay_feeder1.jpg"],
    stockQuantity: 65,
    isActive: true,
    tags: ["rabbit", "hay", "feeder", "small pets"],
    ownerId: "store_hop",
  },
  {
    name: "Bird Cuttlebone Calcium Block",
    description:
      "Essential calcium supplement for parrots, parakeets, and other birds.",
    sku: "BIRD-CALCBLOCK-001",
    barcode: "5678901234567",
    price: 4.25,
    salePrice: 3.99,
    image: "https://example.com/images/bird_cuttlebone.jpg",
    images: ["https://example.com/images/bird_cuttlebone1.jpg"],
    stockQuantity: 120,
    isActive: true,
    tags: ["bird", "calcium", "health"],
    ownerId: "store_feather",
  },
  {
    name: "Dog Flea and Tick Collar",
    description:
      "Up to 8 months protection against fleas and ticks. Waterproof.",
    sku: "DOG-FLEACO-001",
    barcode: "6789012345678",
    price: 31.5,
    salePrice: 25.0,
    image: "https://example.com/images/flea_tick_collar.jpg",
    images: [],
    stockQuantity: 70,
    isActive: true,
    tags: ["dog", "flea", "tick", "collar"],
    ownerId: "store_paw",
  },
  {
    name: "Puppy Training Pads (50-Pack)",
    description: "Super-absorbent, leak-proof pads for house training puppies.",
    sku: "DOG-TRAINPAD-001",
    barcode: "7890123456789",
    price: 19.95,
    salePrice: null,
    image: "https://example.com/images/puppy_training_pads.jpg",
    images: ["https://example.com/images/puppy_training_pads1.jpg"],
    stockQuantity: 250,
    isActive: true,
    tags: ["dog", "puppy", "training", "pads"],
    ownerId: "store_paw",
  },
  {
    name: "Interactive Cat Feather Wand",
    description:
      "Retractable wand with interchangeable feather tips for energetic play sessions.",
    sku: "CAT-TOYWAND-001",
    barcode: "8901234567890",
    price: 7.75,
    salePrice: 6.5,
    image: "https://example.com/images/cat_feather_wand.jpg",
    images: ["https://example.com/images/cat_feather_wand1.jpg"],
    stockQuantity: 130,
    isActive: true,
    tags: ["cat", "toy", "interactive"],
    ownerId: "store_purr",
  },
  {
    name: 'Hamster Exercise Ball (Transparent, 7")',
    description:
      "Let your hamster roam safely—durable plastic, easy-latch closure.",
    sku: "HAMSTER-BALL-001",
    barcode: "9012345678901",
    price: 11.2,
    salePrice: null,
    image: "https://example.com/images/hamster_ball.jpg",
    images: [],
    stockQuantity: 44,
    isActive: true,
    tags: ["hamster", "exercise", "ball", "small pets"],
    ownerId: "store_wheel",
  },
];
